(in-package :cl-user)
(unless (find-package :lisp)
  (defpackage :lisp (:use :cl))
  (do-external-symbols (s :cl) (export s :lisp)))
(unless (find-package :clos)
  (defpackage :clos (:use :cl))
  (do-external-symbols (s :cl) (export s :clos)))
(load "/Users/tatsu-admin/Documents/ChatGPT/New project/codex_sme_impl_2026-10-03/reference_ecl_01/distribution/qrgsetup.lsp")
(setf qrg::*qrg-path* "/Users/tatsu-admin/Documents/ChatGPT/New project/codex_sme_impl_2026-10-03/reference_ecl_01/distribution/" qrg::*action* :load-source)
;; 配布のMac用package設定だけを選ぶ。配布ファイル自体は変更しない。
(let ((*features* (cons :mcl *features*))) (qrg:load-qrg-defsys "v4"))
(qrg:load-sys :sme :action :load-source :verbose nil)
(sme:sme-shakedown)
(dolist (test sme::*sme-tests*)
  (let ((instance (cdr (assoc test sme::*detailed-sme-test-results*))))
    (format t "~&SME-CODEX-ROW~C~A~C~A~C~A~C~A~C~A~C~A~%"
      #\Tab (sme::name test) #\Tab (if (sme::passed? test) 1 0)
      #\Tab (second (assoc :mh-count (sme::sme-tests test)))
      #\Tab (length (sme::mhs instance))
      #\Tab (second (assoc :mapping-count (sme::sme-tests test)))
      #\Tab (length (sme::mappings instance)))))
(quit)
